#+TITLE: Personal Hyprland Configuration with Waybar
#+AUTHOR: Sravan Balaji
#+AUTO_TANGLE: t
#+STARTUP: showeverything

* Table of Contents :TOC_3:noexport:
- [[#welcome][Welcome]]
- [[#hyprland][Hyprland]]
  - [[#monitors][Monitors]]
  - [[#variables][Variables]]
  - [[#autostart][Autostart]]
    - [[#status-bar][Status Bar]]
    - [[#background-processes][Background Processes]]
    - [[#display--compositor-setup][Display / Compositor Setup]]
    - [[#applications][Applications]]
  - [[#environment-variables][Environment Variables]]
  - [[#permissions][Permissions]]
  - [[#look-and-feel][Look and Feel]]
    - [[#general][General]]
    - [[#decoration][Decoration]]
    - [[#animations][Animations]]
    - [[#dwindle-layout][Dwindle Layout]]
    - [[#master-layout][Master Layout]]
    - [[#miscellaneous][Miscellaneous]]
  - [[#input][Input]]
    - [[#keyboard-and-mouse][Keyboard and Mouse]]
    - [[#gestures][Gestures]]
    - [[#device][Device]]
  - [[#keybindings][Keybindings]]
    - [[#binds][Binds]]
    - [[#mod-key][Mod Key]]
    - [[#session-control][Session Control]]
    - [[#launch-programs][Launch Programs]]
    - [[#control-windows--layout][Control Windows / Layout]]
    - [[#move-focus][Move Focus]]
    - [[#switch-workspaces][Switch Workspaces]]
    - [[#move-windows-to-workspace][Move Windows to Workspace]]
    - [[#special-workspace][Special Workspace]]
    - [[#workspace-scroll][Workspace Scroll]]
    - [[#move--resize-windows][Move / Resize Windows]]
    - [[#multimedia-keys][Multimedia Keys]]
  - [[#windows-and-workspaces][Windows and Workspaces]]
    - [[#window-rules][Window Rules]]
    - [[#smart-gaps][Smart Gaps]]
  - [[#graphics][Graphics]]
    - [[#xwayland][XWayland]]
    - [[#opengl][OpenGL]]
    - [[#render][Render]]
  - [[#ecosystem][Ecosystem]]
- [[#xdg-desktop-portal-hyprland][xdg-desktop-portal-hyprland]]
  - [[#screencopy][Screencopy]]
- [[#hypridle][Hypridle]]
  - [[#general-1][General]]
  - [[#listeners][Listeners]]
- [[#hyprlock][Hyprlock]]
  - [[#general-2][General]]
- [[#waybar][Waybar]]
  - [[#start-configuration][Start Configuration]]
  - [[#bar][Bar]]
    - [[#configuration][Configuration]]
    - [[#styling][Styling]]
  - [[#modules][Modules]]
    - [[#battery][Battery]]
    - [[#cpu][CPU]]
    - [[#clock][Clock]]
    - [[#dunst][Dunst]]
    - [[#disk][Disk]]
    - [[#hyprland-1][Hyprland]]
    - [[#idle-inhibitor][Idle Inhibitor]]
    - [[#memory][Memory]]
    - [[#playerctl][Playerctl]]
    - [[#power-menu][Power Menu]]
    - [[#pulseaudio][Pulseaudio]]
    - [[#system76-power][System76 Power]]
    - [[#tray][Tray]]
  - [[#end-configuration][End Configuration]]

* Welcome

My personal configuration of Hyprland, written as an [[https://orgmode.org][Org Mode]] document.

Run the block below with ~C-c C-c~ to tangle code blocks to config file.

#+BEGIN_SRC emacs-lisp :tangle no
(org-mode-restart)
(org-babel-tangle)
#+END_SRC

* Hyprland

- [[https://wiki.hyprland.org/Configuring][Hyprland Wiki - Configuring]]

** Monitors

- [[https://wiki.hyprland.org/Configuring/Monitors][Hyprland Wiki - Configuring - Monitors]]

#+BEGIN_EXAMPLE conf
monitor = name, resolution, position, scale
#+END_EXAMPLE

#+BEGIN_SRC conf :tangle hyprland.conf
monitor = , preferred, auto, 1
#+END_SRC

** Variables

- [[https://wiki.hyprland.org/Configuring/Keywords][Hyprland Wiki - Configuring - Keywords]]

#+BEGIN_SRC conf :tangle hyprland.conf
$terminal = foot
$fileManager = thunar
$menu = rofi -show combi -run-command "uwsm app -- {cmd}"
#+END_SRC

** Autostart

Autostart necessary processes (like notifications daemons, status bars, etc.)
Or execute your favorite apps at launch like this:

#+BEGIN_EXAMPLE conf
exec-once = $terminal
exec-once = nm-applet &
exec-once = waybar & hyprpaper & firefox
#+END_EXAMPLE

If using =uwsm=, prefix application startup commands with =uwsm app --=:

#+BEGIN_EXAMPLE conf
exec-once = uwsm app -- mycommand --arg1 --arg2
bind = SUPER, E, exec, uwsm app -- pcmanfm-qt.desktop
#+END_EXAMPLE

*** Status Bar

#+BEGIN_SRC conf :tangle hyprland.conf
exec-once = uwsm app -- waybar --config $HOME/.config/hypr/waybar/config.jsonc --style $HOME/.config/hypr/waybar/style.css &
#+END_SRC

*** Background Processes

#+BEGIN_SRC conf :tangle hyprland.conf
exec-once = uwsm app -- kdeconnectd --replace &
exec-once = uwsm app -- $HOME/.scripts/dunst.sh --on &
exec-once = uwsm app -- wl-paste --type text --watch cliphist store &
exec-once = uwsm app -- wl-paste --type image --watch cliphist store &
#+END_SRC

*** Display / Compositor Setup

#+BEGIN_SRC conf :tangle hyprland.conf
exec-once = uwsm app -- shikane &
exec-once = uwsm app -- $HOME/.azotebg &
exec-once = uwsm app -- gammastep -x &
#+END_SRC

*** Applications

#+BEGIN_SRC conf :tangle hyprland.conf
exec-once = uwsm app -- blueman-applet &
exec-once = uwsm app -- nm-applet &
exec-once = uwsm app -- kdeconnect-indicator &
exec-once = uwsm app -- udiskie -a -n -s &
exec-once = uwsm app -- nextcloud &
exec-once = uwsm app -- syncthing-gtk &
exec-once = uwsm app -- openrgb &
#+END_SRC

** Environment Variables

- [[https://wiki.hyprland.org/Configuring/Environment-variables/][Hyprland Wiki - Configuring - Environment Variables]]

=uwsm= users should avoid placing environment variables here. Instead, use =~/.config/uwsm/env= for theming, xcursor, nvidia and toolkit variables, and =~.config/uwsm/env-hyprland= for =HYPR*= and =AQ_*= variables. The format is =export KEY=VAL=.

#+BEGIN_EXAMPLE conf
export XCURSOR_SIZE=24
#+END_EXAMPLE

See [[https://github.com/Vladimir-csp/uwsm?tab=readme-ov-file#4-environments-and-shell-profile][uwsm readme]] for additional information.

** Permissions

- [[https://wiki.hyprland.org/Configuring/Permissions/][Hyprland Wiki - Configuring - Permissions]]

#+BEGIN_EXAMPLE conf
ecosystem {
    enforce_permissions = true
}

permission = /usr/(bin|local/bin)/grim, screencopy, allow
permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow
#+END_EXAMPLE

** Look and Feel

- [[https://wiki.hyprland.org/Configuring/Variables/][Hyprland Wiki - Configuring - Variables]]

*** General

- [[https://wiki.hyprland.org/Configuring/Variables/#general][Hyprland Wiki - Configuring - Variables - General]]
- [[https://wiki.hyprland.org/Configuring/Variables/#variable-types][Hyprland Wiki - Configuring - Variables - Variable Types]]
- [[https://wiki.hyprland.org/Configuring/Tearing/][Hyprland Wiki - Configuring - Tearing]]

#+BEGIN_SRC conf :tangle hyprland.conf
general {
    border_size = 2
    no_border_on_floating = false

    gaps_in = 20
    gaps_out = 30
    gaps_workspaces = 0

    col.active_border = rgba(bd93f9ff) rgba(8be9fdff) 45deg
    col.inactive_border = rgba(282a36ff)

    layout = master

    resize_on_border = false

    allow_tearing = false
}
#+END_SRC

*** Decoration

- [[https://wiki.hyprland.org/Configuring/Variables/#decoration][Hyprland Wiki - Configuring - Variables - Decoration]]
- [[https://wiki.hyprland.org/Configuring/Variables/#blur][Hyprland Wiki - Configuring - Variables - Blur]]

#+BEGIN_SRC conf :tangle hyprland.conf
decoration {
    rounding = 10
    rounding_power = 4.0

    active_opacity = 1.0
    inactive_opacity = 1.0
    fullscreen_opacity = 1.0

    dim_inactive = false

    blur {
        enabled = true
        size = 8
        passes = 1
        ignore_opacity = true
        new_optimizations = true
        xray = true

        noise = 0.0117
        contrast = 0.8916
        brightness = 1.0
        vibrancy = 0.1696
        vibrancy_darkness = 0.0

        special = false
        popups = false
        input_methods = false
    }

    shadow {
        enabled = true
        range = 4
        render_power = 3
        color = rgba(1a1a1aee)
        scale = 1.0
    }
}
#+END_SRC

*** Animations

- [[https://wiki.hyprland.org/Configuring/Variables/#animations][Hyprland Wiki - Configuring - Variables - Animations]]

#+BEGIN_EXAMPLE conf
animation = NAME, ONOFF, SPEED, CURVE [,STYLE]
#+END_EXAMPLE

- =ONOFF= can be either 0 or 1, 0 to disable, 1 to enable. /note/: if it's 0, you can omit further args.
- =SPEED= is the amount of ds (1ds = 100ms) the animation will take
- =CURVE= is the bezier curve name, see [[https://wiki.hyprland.org/Configuring/Animations/#curves][curves]]
- =STYLE= (optional) is the animation style

The animations are a tree. If an animation is unset, it will inherit its parent's values. See [[https://wiki.hyprland.org/Configuring/Animations/#animation-tree][the animation tree]].

#+BEGIN_EXAMPLE conf
animation = workspaces, 1, 8, default
animation = windows, 1, 10, myepiccurve, slide
animation = fade, 0
#+END_EXAMPLE

#+BEGIN_SRC conf :tangle hyprland.conf
animations {
    enabled = true
    first_launch_animation = true

    bezier = easeOutQuint,0.23,1,0.32,1
    bezier = easeInOutCubic,0.65,0.05,0.36,1
    bezier = linear,0,0,1,1
    bezier = almostLinear,0.5,0.5,0.75,1.0
    bezier = quick,0.15,0,0.1,1

    animation = global, 1, 10, default
    animation = border, 1, 5.39, easeOutQuint
    animation = windows, 1, 4.79, easeOutQuint
    animation = windowsIn, 1, 4.1, easeOutQuint, popin 87%
    animation = windowsOut, 1, 1.49, linear, popin 87%
    animation = fadeIn, 1, 1.73, almostLinear
    animation = fadeOut, 1, 1.46, almostLinear
    animation = fade, 1, 3.03, quick
    animation = layers, 1, 3.81, easeOutQuint
    animation = layersIn, 1, 4, easeOutQuint, fade
    animation = layersOut, 1, 1.5, linear, fade
    animation = fadeLayersIn, 1, 1.79, almostLinear
    animation = fadeLayersOut, 1, 1.39, almostLinear
    animation = workspaces, 1, 1.94, almostLinear, fade
    animation = workspacesIn, 1, 1.21, almostLinear, fade
    animation = workspacesOut, 1, 1.94, almostLinear, fade
}
#+END_SRC

*** Dwindle Layout

- [[https://wiki.hyprland.org/Configuring/Dwindle-Layout/][Hyprland Wiki - Configuring - Dwindle Layout]]

#+BEGIN_SRC conf :tangle hyprland.conf
dwindle {
    pseudotile = true # Master switch for pseudotiling. See keybinding section to enable
    preserve_split = true # You probably want this
}
#+END_SRC

*** Master Layout

- [[https://wiki.hyprland.org/Configuring/Master-Layout/][Hyprland Wiki - Configuring - Master Layout]]

#+BEGIN_SRC conf :tangle hyprland.conf
master {
    allow_small_split = false
    special_scale_factor = 1.0
    mfact = 0.5
    new_status = master
    new_on_top = true
    new_on_active = none
    orientation = left
    inherit_fullscreen = true
    smart_resizing = true
    drop_at_cursor = true
    always_keep_position = false
}
#+END_SRC

*** Miscellaneous

- [[https://wiki.hyprland.org/Configuring/Variables/#misc][Hyprland Wiki - Configuring - Variables - Misc]]

#+BEGIN_SRC conf :tangle hyprland.conf
misc {
    disable_hyprland_logo = false # If true disables the random hyprland logo / anime girl background. :(
    disable_splash_rendering = false
    force_default_wallpaper = -1 # Set to 0 or 1 to disable the anime mascot wallpapers
    vfr = true
    vrr = 3
    mouse_move_enables_dpms = true
    key_press_enables_dpms = true
}
#+END_SRC

** Input

*** Keyboard and Mouse

- [[https://wiki.hyprland.org/Configuring/Variables/#input][Hyprland Wiki - Configuring - Variables - Input]]

#+BEGIN_SRC conf :tangle hyprland.conf
input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    numlock_by_default = true

    accel_profile = flat
    sensitivity = 0.0
    follow_mouse = 1

    scroll_method = 2fg

    touchpad {
        disable_while_typing = false
        natural_scroll = true
        scroll_factor = 0.5
        tap-to-click = true
    }
}
#+END_SRC

*** Gestures

- [[https://wiki.hyprland.org/Configuring/Variables/#gestures][Hyprland Wiki - Configuring - Variables - Gestures]]

#+BEGIN_SRC conf :tangle hyprland.conf
gestures {
    workspace_swipe = true
    workspace_swipe_fingers = 3
    workspace_swipe_min_fingers = true
}
#+END_SRC

*** Device

- [[https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs][Hyprland Wiki - Configuring - Per Device Input Configs]]

#+BEGIN_EXAMPLE conf
device {
    name = epic-mouse-v1
    sensitivity = -0.5
}
#+END_EXAMPLE

** Keybindings

- [[https://wiki.hyprland.org/Configuring/Keywords/][Hyprland Wiki - Configuring - Keywords]]
- [[https://wiki.hyprland.org/Configuring/Binds/][Hyprland Wiki - Configuring - Binds]]

#+BEGIN_EXAMPLE
bind = MODS, key, dispatcher, params
#+END_EXAMPLE

l -> locked, will also work when an input inhibitor (e.g. a lockscreen) is active.
r -> release, will trigger on release of a key.
c -> click, will trigger on release of a key or button as long as the mouse cursor stays inside binds:drag_threshold.
g -> drag, will trigger on release of a key or button as long as the mouse cursor moves outside binds:drag_threshold.
o -> longPress, will trigger on long press of a key.
e -> repeat, will repeat when held.
n -> non-consuming, key/mouse events will be passed to the active window in addition to triggering the dispatcher.
m -> mouse, see below.
t -> transparent, cannot be shadowed by other binds.
i -> ignore mods, will ignore modifiers.
s -> separate, will arbitrarily combine keys between each mod/key, see [Keysym combos](#keysym-combos) above.
d -> has description, will allow you to write a description for your bind.
p -> bypasses the app's requests to inhibit keybinds.

*** Binds

#+BEGIN_SRC conf :tangle hyprland.conf
binds {
    pass_mouse_when_bound = false
    workspace_back_and_forth = false
    allow_workspace_cycles = false
    workspace_center_on = 1
    focus_preferred_method = 0
    movefocus_cycles_fullscreen = false
    window_direction_monitor_fallback = true
}
#+END_SRC

*** Mod Key

#+BEGIN_SRC conf :tangle hyprland.conf
$mainMod = SUPER # Sets "Windows" key as main modifier
#+END_SRC

*** Session Control

#+BEGIN_SRC conf :tangle hyprland.conf
bind = $mainMod SHIFT, Q, exec, loginctl terminate-user ""
#+END_SRC

*** Launch Programs

#+BEGIN_SRC conf :tangle hyprland.conf
bind = $mainMod SHIFT, Return, exec, uwsm app -- $terminal
bind = $mainMod, E, exec, uwsm app -- $fileManager
bind = $mainMod, P, exec, uwsm app -- $menu
bind = $mainMod CTRL, P, exec, uwsm app -- $HOME/.scripts/control-center.sh --rofi
bind = $mainMod CTRL, C, exec, uwsm app -- cliphist list | rofi -dmenu | cliphist decode | wl-copy
bind = $mainMod CTRL, D, exec, uwsm app -- $HOME/.scripts/brightness.sh --rofi
bind = $mainMod CTRL, V, exec, uwsm app -- $HOME/.scripts/pactl.sh --rofi
bind = $mainMod CTRL, M, exec, uwsm app -- $HOME/.scripts/playerctl.sh --rofi
bind = $mainMod CTRL, N, exec, uwsm app -- $HOME/.scripts/dunst.sh --rofi
bind = $mainMod CTRL, Q, exec, uwsm app -- $HOME/.scripts/session.sh --rofi
#+END_SRC

*** Control Windows / Layout

General

#+BEGIN_SRC conf :tangle hyprland.conf
bind = $mainMod SHIFT, C, killactive
bind = $mainMod SHIFT, F, fullscreen
bind = $mainMod, F, togglefloating
#+END_SRC

Dwindle Layout

#+BEGIN_SRC conf :tangle hyprland.conf
bind = $mainMod, D, pseudo
bind = $mainMod, S, togglesplit
#+END_SRC

Master Layout

#+BEGIN_SRC conf :tangle hyprland.conf
bind = $mainMod, Return, layoutmsg, swapwithmaster auto
#+END_SRC

*** Move Focus

Move focus with mainMod + vim keys

#+BEGIN_SRC conf :tangle hyprland.conf
bind = $mainMod, H, movefocus, l
bind = $mainMod, L, movefocus, r
bind = $mainMod, K, movefocus, u
bind = $mainMod, J, movefocus, d
#+END_SRC

*** Switch Workspaces

Switch workspaces with mainMod + [0-9]

#+BEGIN_SRC conf :tangle hyprland.conf
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10
#+END_SRC

*** Move Windows to Workspace

Move active window to a workspace with mainMod + SHIFT + [0-9]

#+BEGIN_SRC conf :tangle hyprland.conf
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10
#+END_SRC

*** Special Workspace

Example special workspace (scratchpad)

#+BEGIN_EXAMPLE conf
bind = $mainMod, S, togglespecialworkspace, magic
bind = $mainMod SHIFT, S, movetoworkspace, special:magic
#+END_EXAMPLE

*** Workspace Scroll

Scroll through existing workspaces with mainMod + scroll

#+BEGIN_SRC conf :tangle hyprland.conf
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1
#+END_SRC

*** Move / Resize Windows

Move windows with mainMod + SHIFT + vim keys

#+BEGIN_SRC conf :tangle hyprland.conf
bind = $mainMod SHIFT, H, movewindow, l
bind = $mainMod SHIFT, L, movewindow, r
bind = $mainMod SHIFT, K, movewindow, u
bind = $mainMod SHIFT, J, movewindow, d
#+END_SRC

Move/resize windows with mainMod + LMB/RMB and dragging

#+BEGIN_SRC conf :tangle hyprland.conf
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow
#+END_SRC

*** Multimedia Keys

Screenshot

#+BEGIN_SRC conf :tangle hyprland.conf
bind = , print, exec, uwsm app -- grim -g "$(slurp)" - | swappy -f -
#+END_SRC

Volume Controls

#+BEGIN_SRC conf :tangle hyprland.conf
bindel = , XF86AudioRaiseVolume, exec, uwsm app -- $HOME/.scripts/pactl.sh --raise
bindel = , XF86AudioLowerVolume, exec, uwsm app -- $HOME/.scripts/pactl.sh --lower
bindel = , XF86AudioMute, exec, uwsm app -- $HOME/.scripts/pactl.sh --mute
#+END_SRC

Brightness Controls

#+BEGIN_SRC conf :tangle hyprland.conf
bindel = , XF86MonBrightnessUp, exec, uwsm app -- $HOME/.scripts/brightness.sh --raise
bindel = , XF86MonBrightnessDown, exec, uwsm app -- $HOME/.scripts/brightness.sh --lower
#+END_SRC

Media Controls

#+BEGIN_SRC conf :tangle hyprland.conf
bindl = , XF86AudioNext, exec, uwsm app -- $HOME/.scripts/playerctl.sh --next
bindl = , XF86AudioPause, exec, uwsm app -- $HOME/.scripts/playerctl.sh --play-pause
bindl = , XF86AudioPlay, exec, uwsm app -- $HOME/.scripts/playerctl.sh --play-pause
bindl = , XF86AudioPrev, exec, uwsm app -- $HOME/.scripts/playerctl.sh --prev
#+END_SRC

** Windows and Workspaces

- [[https://wiki.hyprland.org/Configuring/Window-Rules/][Hyprland Wiki - Configuring - Window Rules]]
- [[https://wiki.hyprland.org/Configuring/Workspace-Rules/][Hyprland Wiki - Configuring - Workspace Rules]]

*** Window Rules

Example windowrule

#+BEGIN_EXAMPLE conf
windowrule = float,class:^(kitty)$,title:^(kitty)$
#+END_EXAMPLE

Ignore maximize requests from apps. You'll probably like this.

#+BEGIN_SRC conf :tangle hyprland.conf
windowrule = suppressevent maximize, class:.*
#+END_SRC

Fix some dragging issues with XWayland

#+BEGIN_SRC conf :tangle hyprland.conf
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
#+END_SRC

*** Smart Gaps

Example config for enabling smart gaps

#+BEGIN_EXAMPLE conf
workspace = w[tv1], gapsout:0, gapsin:0
workspace = f[1], gapsout:0, gapsin:0
windowrule = bordersize 0, floating:0, onworkspace:w[tv1]
windowrule = rounding 0, floating:0, onworkspace:w[tv1]
windowrule = bordersize 0, floating:0, onworkspace:f[1]
windowrule = rounding 0, floating:0, onworkspace:f[1]
#+END_EXAMPLE

** Graphics

*** XWayland

- [[https://wiki.hyprland.org/Configuring/Variables/#xwayland][Hyprland Wiki - Configuring - Variables - XWayland]]

#+BEGIN_SRC conf :tangle hyprland.conf
xwayland {
    enabled = true
    use_nearest_neighbor = true
    force_zero_scaling = false
    create_abstract_socket = false
}
#+END_SRC

*** OpenGL

- [[https://wiki.hyprland.org/Configuring/Variables/#opengl][Hyprland Wiki - Configuring - Variables - OpenGL]]

#+BEGIN_SRC conf :tangle hyprland.conf
opengl {
    nvidia_anti_flicker = true
}
#+END_SRC

*** Render
- [[https://wiki.hyprland.org/Configuring/Variables/#render][Hyprland Wiki - Configuring - Variables - Render]]

#+BEGIN_SRC conf :tangle hyprland.conf
render {
    explicit_sync = 2
    explicit_sync_kms = 2
    direct_scanout = 2
    expand_undersized_textures = true
    xp_mode = false
    ctm_animation = 2
    cm_fs_passthrough = 2
    cm_enabled = true
}
#+END_SRC

** Ecosystem

- [[https://wiki.hyprland.org/Configuring/Variables/#ecosystem][Hyprland Wiki - Configuring - Variables - Ecosystem]]

#+BEGIN_SRC conf :tangle hyprland.conf
ecosystem {
    no_update_news = true
    no_donation_nag = true
}
#+END_SRC

* xdg-desktop-portal-hyprland

- [[https://wiki.hyprland.org/Hypr-Ecosystem/xdg-desktop-portal-hyprland/#configuration][Hyprland Wiki - Hypr Ecosystem - xdg-desktop-portal-hyprland - Configuration]]

** Screencopy

#+BEGIN_SRC conf :tangle xdph.conf
screencopy {
    max_fps = 0
    allow_token_by_default = false
}
#+END_SRC

* Hypridle

- [[https://wiki.hyprland.org/Hypr-Ecosystem/hypridle/][Hyprland Wiki - Hypr Ecosystem - hypridle]]

** General

#+BEGIN_SRC conf :tangle hypridle.conf
general {
    lock_cmd = pidof hyprlock || hyprlock      # avoid starting multiple hyprlock instances
    before_sleep_cmd = loginctl lock-session   # lock before suspend
    after_sleep_cmd = hyprctl dispatch dpms on # to avoid having to press a key to turn on the display
    ignore_dbus_inhibit = false
    ignore_systemd_inhibit = false
    inhibit_sleep = 2
}
#+END_SRC

** Listeners

Lock screen after 10 minutes

#+BEGIN_SRC conf :tangle hypridle.conf
listener {
    timeout = 600
    on-timeout = loginctl lock-session
}
#+END_SRC

Sleep after 30 minutes

#+BEGIN_SRC conf :tangle hypridle.conf
listener {
    timeout = 1800
    on-timeout = systemctl suspend
}
#+END_SRC

* Hyprlock

- [[https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/][Hyprland Wiki - Hypr Ecosystem - hyprlock]]

** General

- [[https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#general][Hyprland Wiki - Hypr Ecosystem - hyprlock - General]]

#+BEGIN_SRC conf :tangle hyprlock.conf
general {
    hide_cursor = true
    grace = 0
    ignore_empty_input = false
    immediate_render = false
    text_trim = true
    fractional_scaling = 2
    screencopy_mode = 0
    fail_timeout = 2000
}
#+END_SRC

* Waybar

** Start Configuration

#+BEGIN_SRC jsonc :tangle waybar/config.jsonc
// -*- mode: jsonc -*-
{
#+END_SRC

** Bar

*** Configuration

#+BEGIN_SRC jsonc :tangle waybar/config.jsonc
    "layer": "top", // Waybar at top layer
    // "output": "",
    "position": "top", // Waybar position (top|bottom|left|right)
    // "height": 25, // Waybar height (to be removed for auto height)
    // "width": 1280, // Waybar width
    "spacing": 4, // Gaps between modules (4px)
    "mode": "dock",
    "start_hidden": false,
    "fixed-center": true,
    "reload_style_on_change": true,
    "modules-left": [
        "group/power-menu",
        "hyprland/workspaces",
        "hyprland/window",
        "hyprland/submap",
    ],
    "modules-center": [
        "tray",
    ],
    "modules-right": [
        "group/media-playing",
        "pulseaudio",
        "idle_inhibitor",
        "custom/system76-power",
        "cpu",
        "memory",
        "disk",
        "battery",
        "clock",
        "group/dunst",
    ],
    "group/power-menu": {
        "orientation": "inherit",
        "modules": [
            "custom/power-menu-launcher",
            "custom/power-menu-shutdown",
            "custom/power-menu-reboot",
            "custom/power-menu-sleep",
            "custom/power-menu-lock",
            "custom/power-menu-logout",
        ],
        "drawer": {
            "transition-duration": 500,
            "transition-left-to-right": true,
            "click-to-reveal": false,
        },
    },
    "group/media-playing": {
        "orientation": "inherit",
        "modules": [
            "custom/media-playing-source",
            "custom/media-playing-prev",
            "custom/media-playing-play-pause",
            "custom/media-playing-next",
        ],
    },
    "group/dunst": {
        "orientation": "inherit",
        "modules": [
            "custom/dunst-status",
            "custom/dunst-history-view",
            "custom/dunst-clear",
            "custom/dunst-history-clear",
        ],
        "drawer": {
            "transition-duration": 500,
            "transition-left-to-right": true,
            "click-to-reveal": false,
        },
    },
#+END_SRC

*** Styling

#+BEGIN_SRC css :tangle waybar/style.css
window#waybar {
    background: transparent;
}

#window {
    padding: 0px 0px;
    color: transparent;
    background: transparent;
}

widget {
    background: #282a36;
    border-radius: 25px;
}

label.module {
    padding: 0px 10px;
}

button {
    border-radius: 0px;
    padding: 0px 0px;
}

.module,button {
    font-size: 15px;
    font-family: Ubuntu Nerd Font;
}
#+END_SRC

** Modules

*** Battery

**** Configuration

#+BEGIN_SRC jsonc :tangle waybar/config.jsonc
    "battery": {
        "interval": 60,
        "format": "{icon} {capacity}%",
        "format-icons": ["󰂎", "󰁺", "󰁻", "󰁼", "󰁽", "󰁾", "󰁿", "󰂀", "󰂁", "󰂂", "󰁹"],
        "tooltip": true,
        "tooltip-format": "󱧥\t{timeTo}\n󱐋\t{power} W\n󱠴\t{cycles}\n󱈏\t{health}%",
    },
#+END_SRC

**** Styling

#+BEGIN_SRC css :tangle waybar/style.css
#battery {
    background: transparent;
    color: #ff79c6;
}
#+END_SRC

*** CPU

**** Configuration

#+BEGIN_SRC jsonc :tangle waybar/config.jsonc
    "cpu": {
        "interval": 5,
        "format": " {usage}%",
        "tooltip": true,
        "on-click-right": "foot btop",
    },
#+END_SRC

**** Styling

#+BEGIN_SRC css :tangle waybar/style.css
#cpu {
    background: transparent;
    color: #ffb86c;
}
#+END_SRC

*** Clock

**** Configuration

#+BEGIN_SRC jsonc :tangle waybar/config.jsonc
    "clock": {
        "interval": 60,
        "format": "󰥔 {:%I:%M %p}",
        "tooltip": true,
        "tooltip-format": "<tt><small>{calendar}</small></tt>",
        "calendar": {
            "mode"          : "month",
            "mode-mon-col"  : 3,
            "weeks-pos"     : "left",
            "on-scroll"     : 1,
            "format": {
                "months":     "<span color='#50fa7b'><b>{}</b></span>",
                "days":       "<span color='#f8f8f2'><b>{}</b></span>",
                "weeks":      "<span color='#8be9fd'><b>W{}</b></span>",
                "weekdays":   "<span color='#f1fa8c'><b>{}</b></span>",
                "today":      "<span color='#bd93f9'><b><u>{}</u></b></span>"
            },
        },
        "actions": {
            "on-click": "mode",
            "on-click-right": "shift_reset",
            "on-scroll-up": "shift_up",
            "on-scroll-down": "shift_down",
        },
    },
#+END_SRC

**** Styling

#+BEGIN_SRC css :tangle waybar/style.css
#clock {
    background: transparent;
    color: #bd93f9;
}
#+END_SRC

*** Dunst

**** Configuration

#+BEGIN_SRC jsonc :tangle waybar/config.jsonc
    "custom/dunst-status": {
        "exec": "uwsm app -- $HOME/.config/hypr/waybar/scripts/dunst.sh",
        "restart-interval": 1,
        "on-click": "uwsm app -- $HOME/.scripts/dunst.sh --dnd",
        "on-click-right": "uwsm app -- $HOME/.scripts/dunst.sh --rofi",
        "tooltip": true,
        "tooltip-format": "Toggle Do Not Disturb",
    },
    "custom/dunst-clear": {
        "format": "",
        "on-click": "uwsm app -- $HOME/.scripts/dunst.sh --close-all",
        "tooltip": true,
        "tooltip-format": "Close Open Notifications",
    },
    "custom/dunst-history-view": {
        "format": "󰋚",
        "on-click": "uwsm app -- $HOME/.scripts/dunst.sh --history",
        "tooltip": true,
        "tooltip-format": "View Notification History",
    },
    "custom/dunst-history-clear": {
        "format": "󰎟",
        "on-click": "uwsm app -- $HOME/.scripts/dunst.sh --history-clear",
        "tooltip": true,
        "tooltip-format": "Clear Notification History",
    },
#+END_SRC

**** Styling

#+BEGIN_SRC css :tangle waybar/style.css
box#dunst {
    padding: 0px 10px;
}
#custom-dunst-status {
    background: transparent;
    color: #50fa7b;
    padding: 0px 5px;
}
#custom-dunst-clear {
    background: transparent;
    color: #50fa7b;
    padding: 0px 5px;
}
#custom-dunst-history-view {
    background: transparent;
    color: #50fa7b;
    padding: 0px 5px;
}
#custom-dunst-history-clear {
    background: transparent;
    color: #50fa7b;
    padding: 0px 5px;
}
#+END_SRC

**** Script

#+BEGIN_SRC shell :shebang #!/usr/bin/env bash :tangle waybar/scripts/dunst.sh
isPaused=$(dunstctl is-paused)
notificationCount=$(dunstctl count history)

if [[ "$isPaused" == "true" ]]; then
    echo "󰂛 $notificationCount"
else
    echo "󰂚 $notificationCount"
fi
#+END_SRC

*** Disk

**** Configuration

#+BEGIN_SRC jsonc :tangle waybar/config.jsonc
    "disk": {
        "interval": 60,
        "format": "󰋊 {percentage_used}%",
        "tooltip": true,
        "tooltip-format": "Used: {used} ({percentage_used}%)\nFree: {free} ({percentage_free}%)\nTotal: {total}",
        "on-click-right": "uwsm app -- qdirstat",
    },
#+END_SRC

**** Styling

#+BEGIN_SRC css :tangle waybar/style.css
#disk {
    background: transparent;
    color: #f1fa8c;
}
#+END_SRC

*** Hyprland

**** Configuration

#+BEGIN_SRC jsonc :tangle waybar/config.jsonc
    "hyprland/workspaces": {
        "active-only": false,
        "all-outputs": false,
        "format": "{icon}",
        "format-icons": {
		    "1": "󰻧 ₁",
		    "2": "󰍩 ₂",
		    "3": "󰠮 ₃",
		    "4": " ₄",
		    "5": "󰖟 ₅",
            "6": " ₆",
            "7": "󰊢 ₇",
            "8": "󰊖 ₈",
            "9": " ₉",
	    },
        "show-special": true,
        "special-visible-only": true,
        "move-to-monitor": false,
    },
    "hyprland/window": {
        "format": "{title}",
        "rewrite": {
            "": "",
        },
        "separate-outputs": true,
        "icon": true,
        "icon-size": 21,
    },
    "hyprland/submap": {
        "format": "󰘳 {}",
        "default-submap": "",
        "always-on": false,
    },
#+END_SRC

**** Styling

#+BEGIN_SRC css :tangle waybar/style.css
#workspaces {
    padding: 0px 10px;
}
#workspaces button {
    background: transparent;
    color: #f1fa8c;
    padding: 0px 5px;
}
#workspaces button.empty {
    color: #44475a;
}
#workspaces button.active {
    box-shadow: inset 0 -3px #bd93f9;
}
#workspaces button.urgent {
    color: #ff5555;
}
#window {
    background: transparent;
    color: #f8f8f2;
    padding: 0px 10px;
}
#submap {
    background: transparent;
    color: #50fa7b;
    padding: 0px 10px;
}
#+END_SRC

*** Idle Inhibitor

**** Configuration

#+BEGIN_SRC jsonc :tangle waybar/config.jsonc
    "idle_inhibitor": {
        "format": "{icon}",
        "format-icons": {
            "activated": "󱄄 on",
            "deactivated": "󰶐 off",
        },
        "tooltip": true,
        "tooltip-format-activated": "Idle Inhibitor: {status}",
        "tooltip-format-deactivated": "Idle Inhibitor: {status}",
        "start-activated": true,
    },
#+END_SRC

**** Styling

#+BEGIN_SRC css :tangle waybar/style.css
#idle_inhibitor.activated {
    background: transparent;
    color: #f1fa8c;
}
#idle_inhibitor.deactivated {
    background: transparent;
    color: #44475a;
}
#+END_SRC

*** Memory

**** Configuration

#+BEGIN_SRC jsonc :tangle waybar/config.jsonc
    "memory": {
        "interval": 5,
        "format": "  {percentage}%",
        "tooltip": true,
        "tooltip-format": "RAM:\n\tUsed: {used} GiB ({percentage}%)\n\tFree: {avail} GiB\n\tTotal: {total} GiB\nSwap:\n\tUsed: {swapUsed} GiB ({swapPercentage}%)\n\tFree: {swapAvail} GiB\n\tTotal: {swapTotal} GiB",
        "on-click-right": "uwsm app -- foot btop",
    },
#+END_SRC

**** Styling

#+BEGIN_SRC css :tangle waybar/style.css
#memory {
    background: transparent;
    color: #8be9fd;
}
#+END_SRC

*** Playerctl

**** Configuration

#+BEGIN_SRC jsonc :tangle waybar/config.jsonc
    "custom/media-playing-source": {
        "exec": "uwsm app -- $HOME/.config/hypr/waybar/scripts/get-media-playing.sh",
        "return-type": "json",
        "restart-interval": 1,
        "on-click": "uwsm app -- $HOME/.scripts/playerctl.sh --change",
        "tooltip": true,
    },
    "custom/media-playing-prev": {
        "format": "󰒮",
        "on-click": "uwsm app -- $HOME/.scripts/playerctl.sh --prev",
        "tooltip": false,
    },
    "custom/media-playing-play-pause": {
        "exec": "uwsm app -- $HOME/.config/hypr/waybar/scripts/get-media-status-icon.sh",
        "restart-interval": 1,
        "on-click": "uwsm app -- $HOME/.scripts/playerctl.sh --play-pause",
        "tooltip": false,
    },
    "custom/media-playing-next": {
        "format": "󰒭",
        "on-click": "uwsm app -- $HOME/.scripts/playerctl.sh --next",
        "tooltip": false,
    },
#+END_SRC

**** Styling

#+BEGIN_SRC css :tangle waybar/style.css
box#media-playing {
    padding: 0px 10px;
}
#custom-media-playing-source {
    background: transparent;
    color: #ff5555;
    padding: 0px 5px;
}
#custom-media-playing-prev {
    background: transparent;
    color: #ff5555;
    padding: 0px 5px;
}
#custom-media-playing-play-pause {
    background: transparent;
    color: #ff5555;
    padding: 0px 5px;
}
#custom-media-playing-next {
    background: transparent;
    color: #ff5555;
    padding: 0px 5px;
}
#+END_SRC

**** Script

#+BEGIN_SRC shell :shebang #!/usr/bin/env bash :tangle waybar/scripts/get-media-source-icon.sh
mediaStatus=$(playerctl --player=playerctld metadata 2>&1)

if [[ "$mediaStatus" == "No player could handle this command" ]]; then
    echo "󰡀"
else
    trackid=$(playerctl --player=playerctld metadata --format '{{ mpris:trackid }}')
    title=$(playerctl --player=playerctld metadata --format '{{ xesam:title }}')

    if grep -q -i "netflix" <<< "$title"; then
        echo "󰝆"
    elif grep -q -i "hulu" <<< "$title"; then
        echo "󰠩"
    elif grep -q -i "prime video" <<< "$title"; then
        echo ""
    elif grep -q -i "youtube tv" <<< "$title"; then
        echo "󰑈"
    elif grep -q -i "chromium" <<< "$trackid"; then
        echo ""
    elif grep -q -i "vlc" <<< "$trackid"; then
        echo "󰕼"
    elif grep -q -i "spotify" <<< "$trackid"; then
        echo ""
    else
        echo "󰡀"
    fi
fi
#+END_SRC

#+BEGIN_SRC shell :shebang #!/usr/bin/env bash :tangle waybar/scripts/get-media-status-icon.sh
mediaStatus=$(`dirname $0`/get-media-status.sh)

if [[ "$mediaStatus" == "N/A" ]]; then
    echo "󰐎"
else
    if [[ "$mediaStatus" == "Playing" ]]; then
        echo "󰏤"
    elif [[ "$mediaStatus" == "Paused" ]]; then
        echo "󰐊"
    fi
fi
#+END_SRC

#+BEGIN_SRC shell :shebang #!/usr/bin/env bash :tangle waybar/scripts/get-media-status.sh
mediaStatus=$(playerctl --player=playerctld metadata 2>&1)

if [[ "$mediaStatus" == "No player could handle this command" ]]; then
    echo "N/A"
else
    status=$(playerctl --player=playerctld metadata --format '{{ status }}')

    echo $status
fi
#+END_SRC

#+BEGIN_SRC shell :shebang #!/usr/bin/env bash :tangle waybar/scripts/get-media-playing.sh
mediaSourceIcon=$(`dirname $0`/get-media-source-icon.sh)
mediaStatus=$(playerctl --player=playerctld metadata 2>&1)

if [[ "$mediaStatus" == "No player could handle this command" ]]; then
        artist="N/A"
        title="N/A"
        album="N/A"
        status="N/A"
else
        artist=$(playerctl --player=playerctld metadata --format '{{ xesam:artist }}')
        title=$(playerctl --player=playerctld metadata --format '{{ xesam:title }}')
        album=$(playerctl --player=playerctld metadata --format '{{ xesam:album }}')
        status=$(playerctl --player=playerctld metadata --format '{{ status }}')

        if [[ $artist == "" ]]; then
            artist="N/A"
        fi

        if [[ $title == "" ]]; then
            title="N/A"
        fi

        if [[ $album == "" ]]; then
            album="N/A"
        fi

        if [[ $status == "" ]]; then
            status="N/A"
        fi
fi

echo '{"text":"'$mediaSourceIcon'","tooltip":"󰝚\t'${title//'"'/'\"'}'\r󰠃\t'${artist//'"'/'\"'}'\r󰀥\t'${album//'"'/'\"'}'\r󰐎\t'${status//'"'/'\"'}'"}'
#+END_SRC

*** Power Menu

**** Configuration

#+BEGIN_SRC jsonc :tangle waybar/config.jsonc
    "custom/power-menu-launcher": {
        "format": "",
        "on-click": "rofi -show combi -run-command 'uwsm app -- {cmd}'",
        "on-click-right": "uwsm app -- $HOME/.scripts/control-center.sh --rofi",
        "tooltip": true,
        "tooltip-format": "Application Launcher",
    },
    "custom/power-menu-shutdown": {
        "format": "",
        "on-click": "uwsm app -- $HOME/.scripts/session.sh --shutdown",
        "tooltip": true,
        "tooltip-format": "Shutdown",
    },
    "custom/power-menu-reboot": {
        "format": "",
        "on-click": "uwsm app -- $HOME/.scripts/session.sh --reboot",
        "tooltip": true,
        "tooltip-format": "Reboot",
    },
    "custom/power-menu-sleep": {
        "format": "⏾",
        "on-click": "uwsm app -- $HOME/.scripts/session.sh --sleep",
        "tooltip": true,
        "tooltip-format": "Sleep",
    },
    "custom/power-menu-lock": {
        "format": "",
        "on-click": "uwsm app -- $HOME/.scripts/session.sh --lock",
        "tooltip": true,
        "tooltip-format": "Lock",
    },
    "custom/power-menu-logout": {
        "format": "",
        "on-click": "uwsm app -- $HOME/.scripts/session.sh --logout",
        "tooltip": true,
        "tooltip-format": "Logout",
    },
#+END_SRC

**** Styling

#+BEGIN_SRC css :tangle waybar/style.css
box#power-menu {
    padding: 0px 10px;
}
#custom-power-menu-launcher {
    background: transparent;
    color: #8be9fd;
    padding: 0px 5px;
}
#custom-power-menu-shutdown {
    background: transparent;
    color: #ff5555;
    padding: 0px 5px;
}
#custom-power-menu-reboot {
    background: transparent;
    color: #50fa7b;
    padding: 0px 5px;
}
#custom-power-menu-sleep {
    background: transparent;
    color: #f1fa8c;
    padding: 0px 5px;
}
#custom-power-menu-lock {
    background: transparent;
    color: #ff79c6;
    padding: 0px 5px;
}
#custom-power-menu-logout {
    background: transparent;
    color: #ffb86c;
    padding: 0px 5px;
}
#+END_SRC

*** Pulseaudio

**** Configuration

#+BEGIN_SRC jsonc :tangle waybar/config.jsonc
    "pulseaudio": {
        "interval": 5,
        "format": "{icon} {volume}%",
        "format-bluetooth": "{icon} 󰂯 {volume}%",
        "format-muted": "󰝟 muted",
        "format-icons": {
            "hdmi": "󰡁",
            "headset": "󰋎",
            "speaker": "󰓃",
            "headphone": "󰋋",
            "car": "",
            "hifi": "󰤽",
            "default": "",
        },
        "scroll-step": 5,
        "on-click": "uwsm app -- $HOME/.scripts/pactl.sh --mute",
        "on-click-right": "uwsm app -- $HOME/.scripts/pactl.sh --mixer",
        "tooltip": true,
        "tooltip-format": "{desc}",
        "scroll-step": 0.25,
    },
#+END_SRC

**** Styling

#+BEGIN_SRC css :tangle waybar/style.css
#pulseaudio {
    background: transparent;
    color: #ff79c6;
}
#+END_SRC

*** System76 Power

**** Configuration

#+BEGIN_SRC jsonc :tangle waybar/config.jsonc
    "custom/system76-power": {
        "exec": "uwsm app -- $HOME/.config/hypr/waybar/scripts/system76-power.sh",
        "return-type": "json",
        "restart-interval": 60,
        "on-click-right": "uwsm app -- $HOME/.scripts/cpu-gpu.sh --rofi",
        "tooltip": true,
    },
#+END_SRC

**** Styling

#+BEGIN_SRC css :tangle waybar/style.css
#custom-system76-power {
    background: transparent;
    color: #50fa7b;
}
#+END_SRC

**** Script

#+BEGIN_SRC shell :shebang #!/usr/bin/env bash :tangle waybar/scripts/system76-power.sh
profile="$(sudo system76-power profile | sed -z '$ s/\n$//' | tr '\n' '\r')"
graphics="$(sudo system76-power graphics)"
graphicsPower="$(sudo system76-power graphics power)"
chargeThresholds="$(sudo system76-power charge-thresholds | sed -z '$ s/\n$//' | tr '\n' '\r')"

echo '{"text":"󰢮 '$graphics'","tooltip":"󰢮\t'$graphics'\r󰐥\t'$graphicsPower'\r\r  Profile\r'$profile'\r\r󰚥 Charge Thresholds\r'$chargeThresholds'"}'
#+END_SRC

*** Tray

**** Configuration

#+BEGIN_SRC jsonc :tangle waybar/config.jsonc
    "tray": {
        "icon-size": 21,
        "show-passive-items": true,
        "spacing": 4,
        "reverse-direction": false,
    },
#+END_SRC

**** Styling

#+BEGIN_SRC css :tangle waybar/style.css
#tray {
    background: transparent;
    padding: 0px 10px;
}
#+END_SRC

** End Configuration

#+BEGIN_SRC jsonc :tangle waybar/config.jsonc
}
#+END_SRC
